name: hello-world

profiles:
  stable:
    endpoint: /hello/
    max_memory: 0.5G
    max_cpu: 0.5
  canary:
    endpoint: /hello/
    weight: 10 # percentage of traffic to route to this class of deployment
    max_memory: 0.25G
    max_cpu: 0.25
  default:
    name: {{branch.replace('/', '-')}}
    endpoint: /preview/hello/{{branch}}/
    max_memory: 0.25G
    max_cpu: 0.25
